# -*- coding: utf-8 -*-
"""Ejericio 1 BL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/186YNjFEdmPFqEyQykbOXns8tdsor82UU
"""

#AUTOR VARGAS GONZALEZ JORGE YAEL
class Libro:
  def __init__(self, titulo, autor):
    self.titulo = titulo
    self.autor = autor

  def mostrar_informacion(self):
    print(f"Titulo: {self.titulo}")
    print(f"Autor: {self.autor}")

class Libro_Fisico(Libro):
  def __init__(self, titulo, autor, numero_pag):
    super().__init__(titulo, autor)
    self.numero_pag = numero_pag

  def mostrar_informacion(self):
    print("Libro Fisico")
    super().mostrar_informacion()
    print(f"Numero de Paginas: {self.numero_pag}")

class Libro_Digital(Libro):
  def __init__(self, titulo, autor, tamano):
    super().__init__(titulo, autor)
    self.tamano = tamano

  def mostrar_informacion(self):
    print("Libro Digital")
    super().mostrar_informacion()
    print(f"Tamaño: {self.tamano}")

def main():
  libros = []

  while True:
    ingreso = input("Ingrese el tipo de libro (F/D): ").strip().upper()

    if ingreso == "F":
      titulo = input("Ingrese el titulo del libro: ")
      autor = input("Ingrese el autor del libro: ")
      numero_pag = int(input("Ingrese el numero de paginas: "))
      libro = Libro_Fisico(titulo, autor, numero_pag)
    elif ingreso == "D":
      titulo = input("Ingrese el titulo del libro: ")
      autor = input("Ingrese el autor del libro: ")
      tamano = input("Ingrese el tamaño del libro: ")
      libro = Libro_Digital(titulo, autor, tamano)
    else:
      print("Tipo de libro no valido")
      continue

    libros.append(libro)
    print("Libro agregado con exito.")

    opcion = input("Desea agregar otro libro? (S/N): \n").strip().upper()

    if opcion == "N":
      break

  for libro in libros:
    libro.mostrar_informacion()
    print()


if __name__ == "__main__":
  main()