# -*- coding: utf-8 -*-
"""Final Colecciones.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KGQq4uE9EegySm_yrDViitzrSFpc5FQU
"""

#Autor Vargas Gonzalez Jorge Yael

from collections import deque

# Almacenar estudiantes
Lista_estudiantes = []

# Almacenar Datos
Datos_estudiantes = {}

# Almacenar datos cursos
cursos = set()

#Conteo de cursos
curso_conteo = {}

# Cola para estudiantes
cola_estudiantes = deque()

def agregar_estudiante(nombre, semestre, curso):
    id = len(Lista_estudiantes)
    Lista_estudiantes.append(id)
    curso_S = set(curso.split(", "))
    Datos_estudiantes[nombre] = {
        "id" : id,
        "semestre": semestre,
        "nombre": nombre,
        "curso": curso_S
    }
    for c in curso_S:
        if c not in curso_conteo:
            curso_conteo[c] = 1
        else:
            curso_conteo[c] += 1
    cursos.update(curso.split(", "))
    print("\n")
    print(f"Estudiante {nombre} agregado exitosamente")
    print("\n")

def mostrar_estudiantes():
    if not Datos_estudiantes:
        print("\n")
        print("No hay estudiantes que mostrar")
        print("\n")
    else:
        for estudiante in Datos_estudiantes.values():
            print("\n")
            print(f"ID: {estudiante['id']}")
            print(f"Nombre: {estudiante['nombre']}")
            print(f"Semestre: {estudiante['semestre']}")
            print(f"Curso: {', '.join(estudiante['curso'])}")
            print("\n")

def eliminar_estudiante(nombre):
    if nombre in Datos_estudiantes:
        estudiante = Datos_estudiantes[nombre]
        for c in estudiante["curso"]:
            if c in curso_conteo:
                curso_conteo[c] -= 1
                if curso_conteo[c] == 0:
                    cursos.remove(c)
                    del curso_conteo[c]
        del Datos_estudiantes[nombre]
        Lista_estudiantes.remove(estudiante["id"])
        print("\n")
        print(f"Estudiante {nombre} eliminado exitosamente")
        print("\n")
    else:
        print("\n")
        print("Estudiante no encontrado")
        print("\n")

def buscar_estudiante(nombre):
    if nombre in Datos_estudiantes:
        id = Datos_estudiantes[nombre]["id"]
        semestre = Datos_estudiantes[nombre]["semestre"]
        curso = Datos_estudiantes[nombre]["curso"]
        print("\n")
        print(f"Estudiante encontrado: {nombre}")
        print(f"Semestre del estudiante: {semestre}")
        print(f"Curso: {', '.join(curso)}")
        print(f"ID del estudiante: {id}")
        print("\n")
    else:
        print("\n")
        print(f"Estudiante no encontrado")
        print("\n")

def agregar_estudiante_cola(nombre, semestre, curso):
    id = len(Lista_estudiantes)
    Lista_estudiantes.append(id)
    curso_S = set(curso.split(", "))
    cola_estudiantes.append({
        "id" : id,
        "semestre": semestre,
        "nombre": nombre,
        "curso": curso_S
    })
    print("\n")
    print(f"Estudiante {nombre} agregado a la cola exitosamente")
    print("\n")

def Procesar_cola(nombre):
    for i in range(len(cola_estudiantes)):
        estudiante = cola_estudiantes[i]
        if estudiante["nombre"] == nombre:
            cola_estudiantes.remove(estudiante)
            agregar_estudiante(estudiante["nombre"], estudiante["semestre"], ', '.join(estudiante["curso"]))
            print("\n")
            print(f"Estudiante {nombre} procesado exitosamente")
            print("\n")
            return

    print("\n")
    print(f"No hay estudiantes con ese nombre en la cola")
    print("\n")

def mostrar_cola():
    if not cola_estudiantes:
        print("\n")
        print("No hay estudiantes en la cola")
        print("\n")
    else:
        for estudiante in cola_estudiantes:
            print("\n")
            print(f"ID: {estudiante['id']}")
            print(f"Nombre: {estudiante['nombre']}")
            print(f"Semestre: {estudiante['semestre']}")
            print(f"Curso: {', '.join(estudiante['curso'])}")
            print("\n")

def mostrar_cursos():
    print("\n")
    print("Cursos disponibles:")
    for curso in cursos:
        print(curso)
    print("\n")

def menu():
    while True:
        print("Menu Estudiantes")
        print("1. Agregar Estudiante")
        print("2. Mostrar Estudiantes")
        print("3. Eliminar Estudiantes")
        print("4. Buscar Estudiante")
        print("5. Agregar estudiante a cola de espera")
        print("6. Mostrar cola de espera")
        print("7. Procesar cola de espera")
        print("8. Cursos")
        print("9. Salir")

        opcion = int(input("Ingrese una opcion: "))

        if opcion == 1:
            nombre = input("Ingrese el nombre del estudiante: ")
            semestre = input("Ingrese el semestre del estudiante: ")
            curso = input("Ingrese los cursos del estudiante(separado por comas): ")
            agregar_estudiante(nombre, semestre, curso)

        elif opcion == 2:
            mostrar_estudiantes()

        elif opcion == 3:
            nombre = input("Ingrese el nombre del estudiante a eliminar: ")
            eliminar_estudiante(nombre)

        elif opcion == 4:
            nombre = input("Ingrese el nombre del estudiante a buscar: ")
            buscar_estudiante(nombre)

        elif opcion == 5:
            nombre = input("Ingrese el nombre del estudiante a agregar a la cola: ")
            semestre = input("Ingrese el semestre del estudiante: ")
            curso = input("Ingrese los cursos del estudiante(separado por comas): ")
            agregar_estudiante_cola(nombre, semestre, curso)

        elif opcion == 6:
            mostrar_cola()

        elif opcion == 7:
            nombre = input("Ingrese el nombre del estudiante a procesar de la cola: ")
            Procesar_cola(nombre)

        elif opcion == 8:
            mostrar_cursos()

        elif opcion == 9:
            break

        else:
            print("Opcion no valida")
            menu()

menu()